src/library/Yi/Tag.hs
yi.cabal

Remove dependency on utf8-string

---

src/library/Yi/Buffer/HighLevel.hs
src/library/Yi/Dired.hs
src/library/Yi/Editor.hs
src/library/Yi/Paths.hs
src/library/Yi/Snippets.hs
src/library/Yi/UI/Pango/Control.hs

Replace liftM with fmap

---

yi-frontend-vty/src/Yi/Frontend/Vty.hs

Also make it friendly to use by already tying in the
config lens (which I think is how we do most similar
dynamic configurations)

Export baseVtyConfig from vty frontend

---

src/library/Yi/Buffer/Region.hs

This utility function acts like `lines` does for rope, but under
an overlying region so that we can partition a region into its
underlying lines (represented as regions, whose text can be gotten
with `getRegionB`).
This will be useful in implementing a more general version of
:%s for arbitrary selections.
(Note that this doesn't conflict with `split-packages` at all, based on the fact
that I was able to cleanly rebase it back to `master`, so it can easily be
merged into either branch)

Implement linesOfRegionB

---

yi-core/package.yaml
yi-core/src/Yi/CompletionTree.hs
yi-core/yi-core.cabal

Move Yi.Keymap.Completion to Yi.CompletionTree

---

yi-core/package.yaml
yi-core/src/Yi/Buffer/Region.hs
yi-core/src/Yi/Command.hs
yi-core/src/Yi/Hoogle.hs
yi-core/src/Yi/Main.hs
yi-core/src/Yi/Process.hs
yi-core/yi-core.cabal
yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Read.hs

Umm... Can @noughtmare please check to see if anything critical is missing? I'm not understanding what went wrong with this merge, it doesn't look to me like everything got pulled in here?
Maybe some of these commits (particularly like, for example switching to microlens) were somehow already in this branch but git did not know?
Edit: The above seems to be the case and the build is green. Yolo.

Merge master

---

stack.yaml
yi-core/package.yaml
yi-core/src/Yi/CompletionTree.hs
yi-core/test/Spec.hs

Is the Completable class the right way to achieve polymorphism?

Revamped CompletionTree

---

yi-core/src/Yi/Tag.hs

Also removed Typable instance.
Fixes #875

Derived some things directly in Yi.Tag

---

yi-core/package.yaml

I might have added outdated flags (like testing).

Add Flags back in

---

yi-frontend-pango/package.yaml
yi-frontend-pango/src/Yi/Config/Default/Pango.hs
yi-frontend-vty/package.yaml
yi-frontend-vty/src/Yi/Config/Default/Vty.hs
yi-keymap-cua/src/Yi/Config/Default/Cua.hs
yi-keymap-emacs/package.yaml
yi-keymap-emacs/src/Yi/Config/Default/Emacs.hs
yi-keymap-vim/package.yaml
yi-keymap-vim/src/Yi/Config/Default/Vim.hs
yi-misc-modes/package.yaml
yi-misc-modes/src/Yi/Config/Default/MiscModes.hs
yi-mode-haskell/package.yaml
yi-mode-haskell/src/Yi/Config/Default/HaskellMode.hs
yi-mode-javascript/package.yaml
yi-mode-javascript/src/Yi/Config/Default/JavaScriptMode.hs

Fixes #882 
`Yi.Config.Default.JavaScriptMode` is a bit long to type, but I couldn't think of anything else.

Added ConfigM's

---

.travis.yml

Added second travis test for lts.yaml

---

.travis.yml
example-configs/yi-emacs-vty-dynamic/lts.yaml
example-configs/yi-emacs-vty-dynamic/stack.yaml
example-configs/yi-emacs-vty-dynamic/yi-config.cabal
example-configs/yi-emacs-vty-dynamic/yi.hs
example-configs/yi-vim-vty-dynamic/lts.yaml
example-configs/yi-vim-vty-dynamic/stack.yaml
example-configs/yi-vim-vty-dynamic/yi-config.cabal
example-configs/yi-vim-vty-dynamic/yi.hs

This should be merged after #893

Add dynamic vty example configs

---

yi-keymap-vim/src/Yi/Keymap/Vim/ExMap.hs

Saw #927 and thought I'd give it a try. Tested; works for me.

(implement #927) add <C-d> (delete forward word) in Ex mode

---

yi-keymap-vim/package.yaml
yi-keymap-vim/src/Yi/Keymap/Vim/Common.hs
yi-keymap-vim/src/Yi/Keymap/Vim/Ex.hs
yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Registers.hs
yi-keymap-vim/tests/Vim/TestExCommandParsers.hs

Yi can :registers on vim ex mode :smile:

Add vim ex command :registers to listing register details

---

yi-core/src/Yi/Buffer/HighLevel.hs
yi-keymap-emacs/src/Yi/Keymap/Emacs.hs

Fix a paragraph selection for emacs keymap.

---

yi-core/src/Yi/Buffer/Misc.hs

Fix (shortIdentString|identString) document

---

example-configs/yi-all-static/yi-all-static.cabal
example-configs/yi-emacs-vty-static/yi-emacs-vty-static.cabal
example-configs/yi-vim-pango-static/yi-vim-pango-static.cabal
example-configs/yi-vim-vty-static/yi-vim-vty-static.cabal
stack.yaml

I executed `stack resolver --update-config` only :smile: .  
On Arch Linux x86-64.
```console
$ stack --version
Version 1.2.0 x86_64
```

Fix nightly build failing

---

yi-core/src/Parser/Incremental.hs

Doesn't change anything. Adds syntactic sugar in the error correction phase.

Add Functor instance for Profile in Parser

---

yi-keymap-vim/src/Yi/Keymap/Vim/VisualMap.hs
yi-keymap-vim/tests/vimtests/blockvisual/paste_block.test
yi-keymap-vim/tests/vimtests/visual/paste_line.test
yi-keymap-vim/tests/vimtests/visual/paste_multiline.test
yi-keymap-vim/tests/vimtests/visual/paste_word.test
yi-keymap-vim/tests/vimtests/visual/paste_word_2.test

Implement visual paste

---

yi-keymap-vim/src/Yi/Keymap/Vim/StateUtils.hs
yi-language/src/Yi/Lexer/Alex.hs

Fix memory leak

---

yi-core/src/Yi/Command.hs
yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Shell.hs

Use interactive mode for external commands

---

yi-keymap-vim/src/Yi/Keymap/Vim/Ex.hs
yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/BufferNew.hs

Both my pull requests are pre-merged on the master branch of my fork, but I'm still submitting them separately.

Added :new command to vim keymap

---

README.md

Add the overall structure of yi.
It's missing 3 simple useful examples (for BufferM, EditorM and YiM) to be minimally complete.

Configuring part in README

---

README.md

Removed broken links at the top.
Added some cabal commands.

Add detailed installation instructions

---

yi-core/src/Yi/Core.hs
yi-core/src/Yi/UI/Common.hs
yi-dynamic-configuration/src/Yi/Boot/Internal.hs
yi-frontend-vty/src/Yi/Frontend/Vty.hs
yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Quit.hs

`:cq` in Vim Mode

---

yi-keymap-vim/src/Yi/Keymap/Vim/Digraph.hs

Support all two-character RFC1345 digraphs.

---

.travis.yml

This is for testing, probably needs some work still.

Use https://docs.haskellstack.org/en/stable/travis_ci/

---

yi-fuzzy-open/src/Yi/Fuzzy.hs

My case statements got a little out of control. Updating yi-fuzzy-open per @noughtmare's request.

yi-fuzzy-open syntax changes

---

yi-keymap-vim/src/Yi/Keymap/Vim/VisualMap.hs
yi-keymap-vim/tests/vimtests/blockvisual/block_P_1.test
yi-keymap-vim/tests/vimtests/blockvisual/block_P_2.test
yi-keymap-vim/tests/vimtests/blockvisual/block_P_3.test
yi-keymap-vim/tests/vimtests/blockvisual/block_P_4.test
yi-keymap-vim/tests/vimtests/blockvisual/block_p_1.test
yi-keymap-vim/tests/vimtests/blockvisual/block_p_2.test
yi-keymap-vim/tests/vimtests/blockvisual/block_p_3.test
yi-keymap-vim/tests/vimtests/blockvisual/block_p_4.test

See tests for the implemented functionality. I believe this matches parity with vim, but let me know if I should change any of the behavior. Big props to @noughtmare for pointing me in the direction of  [2010ab5](https://github.com/yi-editor/yi/commit/2010ab55e6a4605c3eaf4395afdc25f0a5a63c10).

#1044 Update visual block paste

---

CHANGELOG
yi-misc-modes/src/Yi/Lexer/GitCommit.x

Don't uglify second line of git commit if it is a comment

---

yi-core/src/Yi.hs
yi-core/src/Yi/Buffer/HighLevel.hs
yi-core/src/Yi/Buffer/Indent.hs
yi-core/src/Yi/Buffer/Undo.hs
yi-core/src/Yi/Command.hs
yi-core/src/Yi/Config/Simple.hs
yi-core/src/Yi/Core.hs
yi-core/src/Yi/Dired.hs
yi-core/src/Yi/Editor.hs
yi-core/src/Yi/Eval.hs
yi-core/src/Yi/MiniBuffer.hs
yi-core/src/Yi/Mode/Interactive.hs
yi-core/src/Yi/Process.hs
yi-core/src/Yi/Search.hs
yi-core/src/Yi/String.hs
yi-core/src/Yi/TextCompletion.hs
yi-core/src/Yi/Types.hs
yi-core/src/Yi/UI/Common.hs
yi-core/src/Yi/UI/Utils.hs

yi-core/src/Yi.hs
yi-core/src/Yi/Buffer/HighLevel.hs
yi-core/src/Yi/Buffer/Indent.hs
yi-core/src/Yi/Buffer/Undo.hs
yi-core/src/Yi/Command.hs
yi-core/src/Yi/Config/Simple.hs
yi-core/src/Yi/Core.hs
yi-core/src/Yi/Dired.hs
yi-core/src/Yi/Editor.hs
yi-core/src/Yi/Eval.hs
yi-core/src/Yi/MiniBuffer.hs
yi-core/src/Yi/Mode/Interactive.hs
yi-core/src/Yi/Process.hs
yi-core/src/Yi/Search.hs
yi-core/src/Yi/String.hs
yi-core/src/Yi/TextCompletion.hs
yi-core/src/Yi/Types.hs
yi-core/src/Yi/UI/Common.hs
yi-core/src/Yi/UI/Utils.hs
```sh
$ cat typos.sh
#!/bin/bash
sed -i "s/Succesfully/Successfully/g" yi/yi-core/src/Yi/Search.hs
sed -i "s/broguht/brought/g" yi/yi-core/src/Yi/MiniBuffer.hs
sed -i "s/confguration/configuration/g" yi/yi-core/src/Yi.hs
sed -i "s/dictioary/dictionary/g" …
```

yi-core (typos)
