yi-editor/yi

src/library/Yi/Main.hs
Reverses the order of files in `System.Console.GetOpt`. I'm unable to reproduce the issue with duplicate files, so I'm guessing that magically got fixed somehow.
=> Fix issue #715

src/library/Yi/Keymap/Vim/NormalMap.hs, src/tests/vimtests/change/s_eol.test
Fixes the behavior of 's' in NormalMap
=> Vim: Fix behavior of character replace

src/library/Yi/Buffer/HighLevel.hs, src/library/Yi/UI/SimpleLayout.hs, src/tests/Generic/TestPureBufferManipulations.hs
Yi.UI.SimpleLayout (lastVisiblePointAndWrapCountB) fix word wrap counter; Yi.Buffer.HighLevel (scrollScreensB, scrollByB, vimScrollByB, scrollToCursorB, middleB) use actualLines instead of height
=> Fixes #741 / Word-wrap issue

src/library/Parser/Incremental.hs, src/library/Yi/Config/Default.hs, src/library/Yi/Config/Simple.hs
Fixes ambiguous occurrence of Yi.Keymap.Action (hiding Control.Lens.Action), and reuse functions from Control.Arrow for the incremental parser. To the best of my knowledge, the functions in Control.Arrow and Yi are equivalent.
=> Fix build, and reuse functions

src/library/Yi/Keymap/Vim/VisualMap.hs, src/tests/vimtests/visual/CSs.test
Just a minor change. `s`, `S`, and `C` were unbound in visual mode before this.
=> Vim: Add CSs as aliases to c in visual mode

src/library/Yi/Dired.hs, src/library/Yi/Modes.hs, src/library/Yi/Rectangle.hs, src/library/Yi/UI/Pango.hs, yi.cabal
This mostly just rebases https://github.com/yi-editor/yi/pull/717 onto current master. Additionally, I've bumped up the minimum lens version, and replaced references to Yi.Regex in Dired to use Data.Text.ICU
=> Migrate from regex-tdfa to text-icu

src/library/Yi/Buffer/HighLevel.hs, src/library/Yi/Buffer/Misc.hs, src/library/Yi/Keymap/Vim/Common.hs, src/library/Yi/Keymap/Vim/NormalMap.hs, src/library/Yi/Keymap/Vim/StateUtils.hs, src/library/Yi/Keymap/Vim/Utils.hs, src/library/Yi/Keymap/Vim/VisualMap.hs, src/library/Yi/Types.hs
Useful for fixing #773 
Many of our BufferM functions need to be aware of sticky eols
when dealing with block-style regions. Instead of converting
all of those to EditorM, it makes sense to annotate the buffer
with whether or not sticky eol is enabled.
Sticky eol will never be enabled in the emacs map, and the vim
map now uses the BufferM sticky eol instead of the one internal
to its own state.
To be honest, I'm not sure if moving it to be buffer-local breaks
vim compatibility or not, but it seems to *me* that it should be
local to the buffer and not the editor. And, as mentioned, this is
needed for region-based functions to properly function without
needing this passed in constantly...
This just needs to be sanity checked and then I can merge it if
nobody sees any major issues
=> Make sticky eol local to buffer.

yi.cabal
I don't see any reason to restrict gtk version to `0.13.*` only.
Fixes #784
=> Update gtk version

src/library/Yi/Editor.hs
The code tried to use Show instance for a function.
I don't know where it used to come from but it's not there
anymore. Build fails as:
[ 53 of 145] Compiling Yi.Editor        ( src/library/Yi/Editor.hs, dist/build/Yi/Editor.o )
src/library/Yi/Editor.hs:616:58-61:
No instance for (Show (Window -> WindowRef))
(maybe you haven't applied enough arguments to a function?)
arising from a use of ‘show’
In the first argument of ‘(++)’, namely ‘show wkey’
In the second argument of ‘(++)’, namely
‘show wkey ++ "found. (focusWindowE)"’
In the second argument of ‘($)’, namely
‘"No window with key " ++ show wkey ++ "found. (focusWindowE)"’
Revealed real bug.
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
=> Yi/Editor.hs: Fix build failure

.gitignore, src/library/Yi/Editor.hs, src/library/Yi/Layout.hs, src/library/Yi/UI/SimpleLayout.hs, src/library/Yi/UI/Vty.hs
Currently the **vty** frontend ignores `LayoutManager` and uses a simple vertical stack layout implemented in [SimpleLayout.hs](https://github.com/yi-editor/yi/blob/master/src/library/Yi/UI/SimpleLayout.hs). In particular, you cannot change the divider position in order to, say, have a small console window at the bottom. `LayoutManager` is not as flexible as _XMonad_'s, but it is pretty nice and, as detailed in my comment on #148, can easily be extended with a `UserLayoutManager`.
After the patch the default layout looks like this (note that the main divider, corresponding to the `Pair` constructor, can be moved with `setDividerPosE`):
The basic layouting code was already there: the `layoutToRectangles` function from [Layout.hs](https://github.com/yi-editor/yi/blob/master/src/library/Yi/La …
=> Implement LayoutManager for the vty frontend

src/library/Yi/Keymap/Cua.hs, src/library/Yi/Keymap/Emacs.hs, src/library/Yi/Keymap/Emacs/KillRing.hs, src/library/Yi/Keymap/Vim/Utils.hs, yi.cabal
Addresses #800.
For _Cua_ I updated inplace the `copy`/`paste` functions with the new behavior.
For _Emacs_ I kept the old `EditorM` functions and added new `YiM` functions that also sync the clipboard. I also updated the default bindings to the new ones. This way people can still use the old actions if they want.
For _Vim_ I added the 2 requested functions, but I'm not sure if `pasteFromClipboard` is right, as I'm not very familiar with the _Vim_ code base. I've just seen it done this way in `pasteRegisterBinding` from module [Yi.Keymap.Vim.InsertMap](https://github.com/yi-editor/yi/blob/master/src/library/Yi/Keymap/Vim/InsertMap.hs) but have not tested it yet.
=> System clipboard support with Hclip

src/library/Yi/Core.hs, src/library/Yi/Dired.hs, src/library/Yi/Eval.hs, src/library/Yi/Modes.hs, src/library/Yi/Rectangle.hs
- Removed unused imports
- used `Control.Monad.Except` instead of `Control.Monad.Error` in `Yi/Core.hs`
**I have not tested this with GHC-7.8.**
=> Fixes some GHC warnings (see #808)

src/library/Yi/Main.hs, yi.cabal
Cabal is a pretty big dependency and we use it only for this function.
=> Use Data.Version.showVersion instead of Distribution.Text.display

src/library/Yi/Main.hs
This fixes deprecation errors that weren't fixed in the last
patch (because it wasn't obvious how to remove this).
I decided to try removing the Error instance to see what breaks
and then try to use it some other way. It turns out nothing breaks,
except possibly people's configurations but oh well, its deprecated.
This seems sane to me so I'll push it myself tomorrow assuming
Travis passes.
Fixes #808
=> Rip out Control.Monad.Error.

yi-keymap-vim/package.yaml, yi-keymap-vim/src/Yi/Keymap/Vim/Ex.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Copy.hs, yi-keymap-vim/yi-keymap-vim.cabal
This can be used while #843 is sorted out.
Pasting from clipboard can be done with `:set paste` and `<C-v>` (or `<C-V>` in the vty).
=> Added temporary :copy command

yi-frontend-vty/src/Yi/Frontend/Vty.hs, yi-keymap-vim/package.yaml, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Buffer.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/BufferDelete.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Buffers.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Cabal.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Common.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Copy.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Delete.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Edit.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Global.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Help.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Make.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Quit.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Read.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Shell.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Sort.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Substitute.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Tag.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Write.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Yi.hs, yi-keymap-vim/yi-keymap-vim.cabal
This gets us native text usage and automatic backtracking.
This was pretty much done in a semi-automatic manner, replacing
things like many with many', etc.
Fixes #846
=> Move from Parsec to Attoparsec.

yi-core/package.yaml, yi-core/src/Yi/Dired.hs, yi-core/src/Yi/Mode/Common.hs, yi-core/test/Spec.hs, yi-core/test/Yi/Mode/CommonTests.hs, yi-mode-haskell/src/Yi/Mode/Haskell.hs
Fixes #839.
The only place where `text-icu` is used is now `Yi.Rectangle`, where it's used to align on a regex.
=> Use attoparsec instead of regexes

.travis.yml, lts.yaml, stack.yaml, yi-frontend-pango-gnome/package.yaml, yi-frontend-pango-gnome/src/Yi/Frontend/Pango/Gnome.hs, yi-frontend-pango/package.yaml, yi-frontend-pango/src/Yi/Frontend/Pango.hs, yi-frontend-pango/src/Yi/Frontend/Pango/Control.hs, yi-frontend-pango/src/Yi/Frontend/Pango/Utils.hs
It was a little more involved than just enabling pango in the stack.yaml:
- I removed the gconf dependency (and also the ability to watch for font changes in gnome or something like that), because gconf doesn't build with stack.
- I readded the art data-files to yi-frontend-pango.
- I fixed the indentation, because NondecreasingIndentation was removed in the split-packages branch (as it should be).
- (I also bumped the resolver version).
=> Wire up pango (fixes #867)

yi-core/package.yaml, yi-core/src/Yi/Boot.hs, yi-core/src/Yi/Main.hs, yi-core/src/Yi/Option.hs, yi/src/Main.hs
Allows threading in additional options to do_args (btw, we should
rename this function, why does it have an underscore??). Later we
can move some of the options out of builtins (e.g. dyre options)
and destroy ConsoleConfig.
=> Make options more flexible.

yi-core/src/Yi/Completion.hs, yi-core/src/Yi/MiniBuffer.hs, yi-core/src/Yi/TextCompletion.hs
Improved comment *(to be able to find the function with grep)*, renamed two functions to mirror their actual functionality.
I was actually trying to make an analog of ido-switch-buffer, but wasn't successful, but, at least, noticed some function names that tells little about their purpose.
=> A bit renames

example-configs/yi-emacs-vty-dynamic/yi-config.cabal, example-configs/yi-emacs-vty-dynamic/yi.hs, yi-keymap-emacs/src/Yi/Keymap/Emacs.hs
Port of [the old Emacs config](https://github.com/yi-editor/yi/blob/8f99ba6e6dc49ff71f50607ace54d186de7f7be8/example-configs/yi-simple.hs).
There's also rename `mkKeymap` → `mkKeymapSet` because it is how the same function named in Vim configs *(for consistency)*.
=> Emacs config port

example-configs/yi-all-static/Main.hs, example-configs/yi-all-static/package.yaml, yi/Main.hs, yi/package.yaml
`optparse-applicative-0.13` stops defining its own `(<>)` operator and instead relies on the programmer to use `Data.Monoid.<>`. I don't see a good way of making this backwards compatible without requiring lots of ugly CPP, so I opted to simply require `optparse-applicative-0.13` or later in order to fix this issue.
Fixes #921.
=> Upgrade to use optparse-applicative-0.13

yi-core/src/Yi/Buffer/Misc.hs
For some reason, `yi-core` builds with GHC 8.0.1 but not with 8.0.2, and it appears to be `ImpredicativeTypes`-related. This PR fixes the 8.0.2 build by purging `yi-core` of `ImpredicativeTypes`.
=> Fix build with GHC 8.0.2

yi-core/src/Yi/Buffer/Implementation.hs
BufferImpl is hidden in Yi.Buffer.Implementation,  
but BufferImpl is shown somewhere.
for example) [undoU](https://www.stackage.org/haddock/lts-7.7/yi-0.12.6/Yi-Buffer-Undo.html#v:undoU)
=> Fix document about BufferImpl is hidden

yi-keymap-cua/package.yaml
It seems like it was omitted accidentally since all others are exposed (e.g. configureVty, configureVim...)
=> Expose default Cua config

shell.nix, stack.yaml, yi-core/package.yaml, yi-core/src/Yi/Completion.hs, yi-core/test/Spec.hs, yi-core/test/Yi/CompletionTests.hs
Hello Yi maintainers,
I've found a little bug where an error would occur if you have not typed anything before hitting autocomplete, for example when switching buffers. The error was caused by the partial function Data.Text.breakOn (breakOn "" x  -->  Exception: Data.Text.breakOn: empty input)
This pull request includes:
- the fix
- extra quickcheck properties
- some changes to make yi build
- an improved shell.nix
- an extra-deps line in stack.yaml to make instance ListLike Text Char work (weird but apparently necessary)
=> Completion bugfix

yi-core/src/Yi/Search.hs, yi-frontend-pango/src/Yi/Frontend/Pango/Control.hs, yi-language/src/Yi/Lexer/Compilation.x, yi-language/src/Yi/Regex.hs
Continuing PR #717. This limits the number of functions re-exported by Yi.Regex, which should hopefully make the transition easier.
=> Make regex exports explicit

yi-core/src/Yi/Process.hs
Currently, `yi-core` fails to install on Windows with this error:
```
$ cabal install yi-core
Resolving dependencies...
Configuring yi-core-0.13.5...
Building yi-core-0.13.5...
Failed to install yi-core-0.13.5
Build log ( C:\Users\RyanGlScott\AppData\Roaming\cabal\logs\yi-core-0.13.5.log ):
Building yi-core-0.13.5...
Preprocessing library yi-core-0.13.5...
<build output elided>
[28 of 74] Compiling Yi.Process       ( src\Yi\Process.hs, dist\build\Yi\Process.o )
src\Yi\Process.hs:76:29-49: error:
* Variable not in scope:
runInteractiveProcess
:: FilePath
-> [String]
-> Maybe a1
-> Maybe a0
-> IO (Handle, Handle, Handle, ProcessHandle)
* Perhaps you want to add `runInteractiveProcess'
to the import list in the import of `System.Process'
(src\Yi\Process.hs:15:1-68).
cabal: Leaving directory …
```
=> Fix the Windows build

yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Nohl.hs, yi-keymap-vim/tests/Vim/TestExCommandParsers.hs
Vim accepts all prefixes of `:nohlsearch` that are longer than `:noh`.
=> Support all abbreviations for :nohlsearch

yi-keymap-vim/src/Yi/Keymap/Vim/Motion.hs, yi-keymap-vim/tests/vimtests/find/f6.test, yi-keymap-vim/tests/vimtests/find/t7.test
The problem is that we can't just repeat the `t` and `T` movements n times, because they are idempotent. Instead we really want to do the f or F movement n times and then go back one character. The old buggy solution just skip over one character the first n-1 times instead. This however creates problems if the search targets are right next to each other (see added tests). For example `2fc` skips over three adjacent `c`s and `2tc` will not move at all on two adjacent `c`s because the last move was stationary.
=> Fix behaviour of f,t,F,T when given a count

yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Substitute.hs, yi-keymap-vim/tests/vimtests/ex/s/8.test
This fixes two problems with the substitute ex command.
1. Vim supports another abbreviation `:sub`.
2. In vim you can omit the trailing delimiter if you don't need to pass any flags like so: `:s/x/y`.
=> :substitute optional trailing delimiter

yi-keymap-vim/8.test, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Common.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Delete.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Sort.hs, yi-keymap-vim/tests/vimtests/ex/d/3.test, yi-keymap-vim/tests/vimtests/ex/d/4.test, yi-keymap-vim/tests/vimtests/ex/d/5.test, yi-keymap-vim/tests/vimtests/ex/d/6.test, yi-keymap-vim/tests/vimtests/ex/d/7.test
This fixes a few problems regarding ex ranges:
1. Ex ranges are always linewise. Meaning a command like `:'<,'>d` will delete the whole lines of the selection not just the selected parts. I guess it is debatable whether we want to adopt this behaviour, but in any case relative ranges like `:-1,+1d` should be linewise, so if we decide against this the code for parsing those needs adjustment.
2. `:d` is now able to take a range. Not that I ever use this command, I just noticed it when I wanted to write tests for the new range behaviour.
3. In vim you can write for example `:-1,+1d` but `yi` required you to write `:.-1,.+1d`. This is what I was originally trying to fix.
=> Various fixes regarding ex ranges

shell.nix, stack.yaml, yi-core/bench/Bench.hs, yi-core/package.yaml, yi-core/src/Yi/Buffer/HighLevel.hs, yi-core/src/Yi/Buffer/Implementation.hs, yi-core/src/Yi/Buffer/Misc.hs, yi-core/src/Yi/Buffer/Undo.hs, yi-core/src/Yi/Config/Default.hs, yi-core/src/Yi/Config/Simple.hs, yi-core/src/Yi/Core.hs, yi-core/src/Yi/Editor.hs, yi-core/src/Yi/KillRing.hs, yi-core/src/Yi/Types.hs
We take a small performance hit on operations (due to forcingn Undo) but
performance can be fixed there by not doing silly things. On the other
hand we have 5x+ memory improvement and we aren't leaking everywhere
anymore.
BufferM simple state chain update before/after
----------------------
http://i.imgur.com/F5IvX33.png (WriterT leak)
Basic benchmark, old
----------------------
insert 1million
http://heap.ezyang.com/view/832fbfa170d6741aef9eb56ed60ea5947026b979
yi-core-0.13.5: Benchmark running disabled by --no-run-benchmarks flag.
Completed 2 action(s).
benchmarking split20
time                 913.6 ns   (913.4 ns .. 913.9 ns)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 913.9 ns   (913.6 ns .. 914.2 ns)
std dev              1.004 ns   (759.4 ps .. 1.431 ns)
benchmarking …
=> Improve BufferM memory usage

yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Shell.hs
The previous revision only allowed executing shell commands where the command name consists entirely of the space character.
=> Fixed parser for ":!" vim command

yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Buffer.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/BufferDelete.hs
Previous:
:bdelete ignores the argument, closes the current window if there's another one open.
Version in pull request:
:bdelete with no arguments preserves previous behavior, :bdelete with an argument closes the specified buffer but does not close any windows. This is closer to Vim, but in Vim :bdelete never closes any windows.
=> :bdelete vim command takes argument for which buffer to delete

yi-misc-modes/src/Yi/Lexer/Python.x
Let me know if there's a better way to test this. Here are some screenshots to show you what I've been seeing:
Prior behavior:
With this commit:
Notice, though, that quad-quotes will still break:
=> Fix #1041: Python syntax highlighting for multiline strings

yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Edit.hs
Fixes #829, as far as I can tell.
=> Add completion for ':e ' without a path stub

yi-core/src/Yi/Core.hs, yi-core/src/Yi/Editor.hs
Now `findBufferWithName` will return all buffers that have the input name as infix of their name.
This also adds a function `doesBufferNameExist` that should be used instead of findBufferWithName for exact lookups.
Fixes #1060
=> Make findBufferWithName more lenient

yi-core/src/Yi/Config/Default.hs, yi-core/src/Yi/Config/Simple.hs, yi-core/src/Yi/Types.hs, yi-core/src/Yi/UI/LineNumbers.hs, yi-core/yi-core.cabal, yi-frontend-vty/src/Yi/Frontend/Vty.hs, yi-keymap-vim/README.rst, yi-keymap-vim/src/Yi/Keymap/Vim/Ex.hs, yi-keymap-vim/src/Yi/Keymap/Vim/Ex/Commands/Number.hs, yi-keymap-vim/yi-keymap-vim.cabal
Hello everyone!
This adds vim-style line numbers in vty frontend (as of #1054).
Currently it's not configurable (it displays line numbers for all non-mini windows), because I'm not exactly sure where to configure this. I think in vim, "number" is a property of the window but it can also be set globally, such that new windows are created with numbers on or off. So my guess would be to add fields to the Config and Window records and then create new windows with the number setting according to the number setting in Config.
Feedback appreciated :)
=> Show line numbers in vty frontend

yi-misc-modes/src/Yi/Lexer/Ruby.x
Previous behaviour: symbols such as `:abcDef` would be highlighted in two different colours. This patch highlights the entire symbol in a single colour.
=> Ruby highlighter: slightly more correct symbol syntax

yi/Main.hs
Current yi shows '0.16.0' by running "yi --version".
This PR always shows yi-package's version.
=> Use package-version to show cli-version

yi-intero/README.md, yi-keymap-emacs/src/Yi/Keymap/Emacs/Utils.hs, yi-keymap-vim/src/Yi/Keymap/Vim/NormalMap.hs, yi-keymap-vim/src/Yi/Keymap/Vim/TextObject.hs, yi-keymap-vim/tests/Generic/TestUtils.hs, yi-language/src/Yi/Style.hs, yi-language/src/Yi/Syntax.hs, yi-misc-modes/src/Yi/Lexer/GNUMake.x, yi-misc-modes/src/Yi/Lexer/Perl.x, yi-mode-haskell/src/Yi/Syntax/Haskell.hs, yi-snippet/README.rst
yi-intero/README.md
yi-keymap-emacs/src/Yi/Keymap/Emacs/Utils.hs
yi-keymap-vim/src/Yi/Keymap/Vim/NormalMap.hs
yi-keymap-vim/src/Yi/Keymap/Vim/TextObject.hs
yi-keymap-vim/tests/Generic/TestUtils.hs
yi-language/src/Yi/Style.hs
yi-language/src/Yi/Syntax.hs
yi-misc-modes/src/Yi/Lexer/GNUMake.x
yi-misc-modes/src/Yi/Lexer/Perl.x
yi-mode-haskell/src/Yi/Syntax/Haskell.hs
yi-snippet/README.rst
```sh
$ cat typos.sh
#!/bin/bash
sed -i "s/Avaliable/Available/g" yi/yi-snippet/README.rst
sed -i "s/Coresponds/Corresponds/g" yi/yi-keymap-emacs/src/Yi/Keymap/Emacs/Utils.hs
sed -i "s/Horizantal/Horizontal/g" yi/yi-keymap-vim/src/Yi/Keymap/Vim/NormalMap.hs
sed -i "s/Theese/These/g" yi/yi-mode-haskell/src/Yi/Syntax/Haskell.hs
sed -i "s/abstrcted/abstracted/g" yi/yi-language/src/Yi/Syntax.hs
sed -i …
```
=> typo fixes

yi-core/src/Yi/Dired.hs, yi-frontend-pango/src/Yi/Frontend/Pango/Control.hs, yi-frontend-vty/yi-frontend-vty.cabal, yi-language/src/Yi/Lexer/Compilation.x, yi-language/src/Yi/Lexer/common.hsinc, yi-misc-modes/src/Yi/Lexer/common.hsinc, yi-mode-haskell/src/Yi/Lexer/common.hsinc, yi-mode-javascript/src/Yi/Lexer/common.hsinc
This gets `cabal build all --allow-newer -c 'vty<6'` working on GHC 9.10.1.
=> Allow building with newer dependencies
